CREATE TABLE tb1(A int, B int, PRIMARY KEY (A));
CREATE TABLE tb2(C int, D int, FOREIGN KEY (C) REFERENCES tb1(A));
LOAD DATA LOCAL INFILE '~/www/P2/test1.txt' INTO TABLE tb1;
LOAD DATA LOCAL INFILE '~/www/P2/test2.txt' INTO TABLE tb2;